#22.04
network:
  ethernets:
    home:
      #dhcp4: true
      dhcp4: false
      routes:
        - to: default
          via: #gtaeway ip
      match:
        macaddress: #ras mac
 #this is bridge network macaddress
      addresses: # this is ras ip(static)
      nameservers:
        addresses: [8.8.8.8]
      set-name: home
  version: 2
  renderer: networkd
