#22.04
network:
  ethernets:
    home:
      #dhcp4: true
      dhcp4: false
      routes:
        - to: default
          via: a.b.c.d #gtaeway ip
      match:
        macaddress: #ras mac
 #this is bridge network macaddress
      addresses: [A.B.C.D/24] # this is ras ip(static) for 255.255.255.0
      nameservers:
        addresses: [8.8.8.8]
      set-name: home
  version: 2
  renderer: networkd
#my ref https://ubuntu.com/server/docs/network-configuration
