#22.04
network:
  ethernets:
    home:
      #dhcp4: true
      dhcp4: false
      routes:
        - to: default
          via: 192.168.0.1 #tenda
      match:
        macaddress: b8:27:eb:ad:f8:72
 #this is bridge network macaddress
      addresses: [192.168.0.101/24] # this is vm's ip(static)
      nameservers:
        addresses: [8.8.8.8]
      set-name: home
  version: 2
  renderer: networkd
