# This is the network config written by 'subiquity'
network:
  ethernets:
     home:
      #dhcp4: true
      dhcp4: false
      #gateway4: 192.168.1.1
      match:
          macaddress: ab:cd:ef:11:22:33 #this is bridge network macaddress
      addresses: [1.1.1.1/24] # this is vm's ip(static)
      nameservers:
         addresses: [8.8.8.8]
      set-name: home
  version: 2
  renderer: networkd
